name       : libt1ha
version    : 2.1.4
release    : 1
source     :
    - https://github.com/erthink/t1ha/archive/refs/tags/v2.1.4.tar.gz : b3bc5bf5f337559b9d6f70e6bde1dec3854eb27f2aea51a147e69383fc6b05ef
license    : Zlib
component  : programming.library
summary    : One of the fastest hash functions
description: |
    libt1ha is a portable non-cryptographic 64-bit hash function
# Avoid creating a -devel package for a single header file.
# especially as no make install is provided.
patterns   :
    - /*
build      : |
    %make

    # build libt1ha_pic.a for cve-check-tool...
    # cve-check-tool specifically looks for this although we should probably
    # just patch it's autotools to be able to make use of the shared library.
    make libt1ha.a CFLAGS_LIB='-O3 -DNDEBUG -g0 -ffunction-sections -fpic'
    mv libt1ha{,_pic}.a
install    : |
    # No make install provided
    install -Dm00644 t1ha.h $installdir/usr/include/t1ha.h
    install -Dm00644 libt1ha.so $installdir/%libdir%/libt1ha.so
    ln -sv libt1ha.so $installdir/%libdir%/libt1ha.so.2
    ln -sv libt1ha.so.2 $installdir/%libdir%/libt1ha.so.$version

    # cve-check-tool
    install -Dm00644 libt1ha_pic.a $installdir/%libdir%/libt1ha_pic.a
check     : |
    %make check
